# 쉬운 예제로 한번 보시죠.

In [23]:
c = np.array([[0, 1, 2], [3, 4, 5,]])
c

array([[0, 1, 2],
       [3, 4, 5]])

In [31]:
c.shape

(2, 3)

In [25]:
d = np.array([[6], [9]])
d

array([[6],
       [9]])

In [26]:
d.shape

(2, 1)

In [29]:
ss = np.concatenate((c, d), axis = 1) # for 2D~ array

In [30]:
ss

array([[0, 1, 2, 6],
       [3, 4, 5, 9]])

In [33]:
e = np.array([6, 9])
e

array([6, 9])

In [41]:
e.ndim

1

In [34]:
e.shape

(2,)

In [38]:
ee = e[:, np.newaxis]
ee

array([[6],
       [9]])

In [43]:
ee.shape

(2, 1)

In [44]:
ee.ndim

2

In [14]:
dataset = df.values

In [15]:
type(dataset)

numpy.ndarray

In [16]:
X = dataset[:,0:13]
Y = dataset[:,13]

In [17]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.3) # 얘가 뭘하는 애인가?

In [18]:
print(type(y_train))
print(type(X_train))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [19]:
print(X_train.shape)
print(y_train.shape)

(354, 13)
(354,)


In [20]:
y_train1 = y_train[:, np.newaxis]
y_train1.shape

(354, 1)

In [21]:
tr = np.concatenate((X_train, y_train1), axis = 1) # for 2D~ array
tr.shape

(354, 14)

In [22]:
columns = df.columns
train=pd.DataFrame(tr, columns=columns)

In [23]:
train.head()
# CHA 찰스강에 대한 더미변수(강의 경계에 위한 경우는 1,아니면 0)

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE      DIS  RAD    TAX  \
0  0.10574   0.0  27.74   0.0  0.609  5.983  98.8   1.8681  4.0  711.0   
1  0.10290  30.0   4.93   0.0  0.428  6.358  52.9   7.0355  6.0  300.0   
2  0.17004  12.5   7.87   0.0  0.524  6.004  85.9   6.5921  5.0  311.0   
3  0.07950  60.0   1.69   0.0  0.411  6.579  35.9  10.7103  4.0  411.0   
4  2.14918   0.0  19.58   0.0  0.871  5.709  98.5   1.6232  5.0  403.0   

   PTRATIO       B  LSTAT  target  
0     20.1  390.11  18.07    13.6  
1     16.6  372.75  11.22    22.2  
2     15.2  386.71  17.10    18.9  
3     18.3  370.78   5.49    24.1  
4     14.7  261.95  15.79    19.4

In [24]:
train.shape

(354, 14)